apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: demo-app
      
  template:
    metadata:
      labels:
        app: demo-app

    spec:
      containers:
        - name: react-procution-app
          image:  kopilnagi/react-procution-app:latest
  
          ports:
          - containerPort: 80
